# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/contracts/my-contract" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/contracts/my-contract/deploy-scripts" # Location of package manifests
    schedule:
      interval: "weekly"
